### ISSUE TITLE
Error when run install

### ISSUE THREAD

**Issue by Jeffeditae** [xflash-panda/v2board#1]
I have use v2board before and i change code and i have a mistake is error .
Updating dependencies
Generating rules
Resolving dependencies through SAT

Dependency resolution completed in 0.002 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework[v7.29.0, v7.29.1, v7.29.2, v7.29.3, v7.30.0, v7.30.1, v7.30.2, v7.30.3, v7.30.4, 7.x-dev] require                                                                                                                                                                league/flysystem ^1.1 -> satisfiable by league/flysystem[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.x-dev].
    - league/flysystem[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.x-dev] require ext-fileinfo * -> it is missing from you                                                                                                                                                               r system. Install or enable PHP's fileinfo extension.
    - Root composer.json requires laravel/framework ^7.29 -> satisfiable by laravel/framework[v7.29.0, v7.29.1, v7.29.2, v                                                                                                                                                               7.29.3, v7.30.0, v7.30.1, v7.30.2, v7.30.3, v7.30.4, 7.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - /www/server/php/73/etc/php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
PHP Warning:  require(/www/wwwroot/jeffeditae.studio/vendor/autoload.php): failed to open stream: No such file or director                                                                                                                                                               y in /www/wwwroot/jeffeditae.studio/artisan on line 18

Warning: require(/www/wwwroot/jeffeditae.studio/vendor/autoload.php): failed to open stream: No such file or directory in                                                                                                                                                                /www/wwwroot/jeffeditae.studio/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/jeffeditae.studio/vendor/autoload.php' (include_path='.                                                                                                                                                               :/www/server/php/73/lib/php') in /www/wwwroot/jeffeditae.studio/artisan on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/jeffeditae.studio/vendor/autoload.php' (include_path='.:/www                                                                                                                                                               /server/php/73/lib/php') in /www/wwwroot/jeffeditae.studio/artisan on line 18
PHP Warning:  require(/www/wwwroot/jeffeditae.studio/vendor/autoload.php): failed to open stream: No such file or director                                                                                                                                                               y in /www/wwwroot/jeffeditae.studio/artisan on line 18

Warning: require(/www/wwwroot/jeffeditae.studio/vendor/autoload.php): failed to open stream: No such file or directory in                                                                                                                                                                /www/wwwroot/jeffeditae.studio/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/jeffeditae.studio/vendor/autoload.php' (include_path='.                                                                                                                                                               :/www/server/php/73/lib/php') in /www/wwwroot/jeffeditae.studio/artisan on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/jeffeditae.studio/vendor/autoload.php' (include_path='.:/www                                                                                                                                                               /server/php/73/lib/php') in /www/wwwroot/jeffeditae.studio/artisan on line 18
[root@TEST jeffeditae.studio]#

In command sh init.sh
I hope you can teach how can install

**Comment by himanhimao** [comment]
you have not installed the FileInfo extension
