### ISSUE TITLE
邮件：Cannot send message without a sender address

### ISSUE THREAD

**Issue by mashirozx** [xflash-panda/v2board#11]
admin ui界面上邮件页面全部字段都填写了。邮件服务商：yeah.net、outlook.com

**Comment by mashirozx** [comment]
配置页上的测试是OK的但是其他地方发送邮件会出现这个错误，比如忘记密码页面 /forget

**Comment by himanhimao** [comment]
好的 我测试一下

**Comment by himanhimao** [comment]
> 配置页上的测试是OK的但是其他地方发送邮件会出现这个错误，比如忘记密码页面 /forget

我在demo站做了测试，没有发现，因为引入了provider,有可能您的配置缓存需要更新一下， 需要执行`php artisan config:clear`

**Comment by himanhimao** [comment]
> > 配置页上的测试是OK的但是其他地方发送邮件会出现这个错误，比如忘记密码页面 /forget
> 
> 我在demo站做了测试，没有发现，因为引入了provider,有可能您的配置缓存需要更新一下， 需要执行`php artisan config:clear`

或者你的队列job需要重启一下

**Comment by mashirozx** [comment]
哦哦，确实是，队列重启以后就好了，谢谢~
