### ISSUE TITLE
ga tag应该做成选项吧

### ISSUE THREAD

**Issue by mashirozx** [xflash-panda/v2board#13]
https://github.com/xflash-panda/v2board/blob/master/public/theme/v2board/dashboard.blade.php#L66

**Comment by himanhimao** [comment]
可以做成选项，但是好像不太好实现，
因为要考虑前后端分离的情况， 现在是内嵌在PHP执行的，是可以通过模板直接读取配置实现的，如果分离的话，就不能读配置了，我没有想到好的方式去兼容。

**Comment by mashirozx** [comment]
或许前后分离的引导一下自行去index.html修改就可以了

**Comment by himanhimao** [comment]
> 或许前后分离的引导一下自行去index.html修改就可以了

所以这种情况选项就失效了，感觉不够完美，再想想吧
