### ISSUE TITLE
local.ERROR: App\Jobs\SendEmailJob has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\SendEmailJob has been attempted too many times or run too long. The job may have previously timed out. at /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:648)

### ISSUE THREAD

**Issue by mashirozx** [xflash-panda/v2board#17]

**Comment by himanhimao** [comment]
我感觉这个速率器加的位置不对，它工作在一个JOB中，每个JOB单独执行一个发送任务，并且是独立的，所以在这限速可能没有意义。

**Comment by mashirozx** [comment]
这个middleware可以保证一分钟内只有若干个JOB执行，如果超限就[release the job back into the queue](https://github.com/spatie/laravel-rate-limited-job-middleware/blob/main/src/RateLimited.php#L175)，待若干时间以后再retry

如果是laravel 8 倒是有[原生的RateLimited方法](https://laravel.com/api/8.x/Illuminate/Queue/Middleware/RateLimited.html)可以用，laravel 7嘛我只找到这个轮子。。

经过测试，确实能实现throttle的效果，但是我不太确定队列的tries设置多大合适。。

**Comment by himanhimao** [comment]
看了下rate middleware的原理 是通过redis 多个job之间进行限速 多个job之间本身是独立状态的，现在会变成共享状态，再加上配置设置了releaseAfterSeconds(90) 导致job超时。所以我认为引入rate middleware 不是一个好的做法。

**Comment by himanhimao** [comment]
另外，对于用户来说，后台需要单独配置，而好多用户是不了解邮件速率的，加上配置也依然有可能导致job超时，job默认超时时间好像是个固定值(假如30s)  所以不管怎么配置，也有可能导致超时情况，并且JOB会占用大量资源。

**Comment by mashirozx** [comment]
单个job的重试次数应该是能通过[retryUntil](https://github.com/spatie/laravel-rate-limited-job-middleware#configuring-attempts)控制的，只要控制好重试次数这个超时其实是在可控范围内的吧

**Comment by mashirozx** [comment]
或者也可以这样？https://laravel.com/docs/master/queues#max-exceptions

**Comment by himanhimao** [comment]
默认JOB 做了两秒的延时，单个job 理论上一分钟会处理30次， 也就是30封邮件，所以我觉得通过控制maxProcesses的JOB数量，可以进行限速

**Comment by himanhimao** [comment]
我看了目前的V2BOARD 的队列管理Horizon 配置做的并不好， 可以单独对send mail的队列数量进行控制做限速。https://laravel.com/docs/8.x/horizon 这是配置文档，目前JOB是动态的， 如果配置了3个JOB 那就是一分钟90封邮件。
所以我觉得通过horizon配置就可以做到很好的限速

**Comment by mashirozx** [comment]
两秒延时是异步的呀
0s
|
|-async job-->2s 后执行
|-async job-->2s 后执行
|-async job-->2s 后执行
| ...
|
1s
这个延时没有意义吧

**Comment by himanhimao** [comment]
不管是异步还是同步，控制JOB数量是可以做到限速的，因为是JOB是基于队列的，上一个任务完成不了，不会进行下一个任务，你认为呢？

> 两秒延时是异步的呀 0s | |-async job-->2s 后执行 |-async job-->2s 后执行 |-async job-->2s 后执行 | ... | 1s 这个延时没有意义吧

**Comment by himanhimao** [comment]
所以不delay queue(如果只是延时队列，那么是无效的）,  也不做job sleep(通过sleep函数，阻塞单个JOB) ,也不引入rate middleware，通过改变hortian配置可以解决这个问题。 你看是不是可以这样解决？

**Comment by himanhimao** [comment]
如果没什么问题 我将rollback 去修复此bug

**Comment by mashirozx** [comment]
好的，我再研究一下

**Comment by mashirozx** [comment]
我试了一下发现频率似乎没控制下来
![](https://user-images.githubusercontent.com/16148054/145592125-956aabe1-a062-4e9c-9c4a-de0a69687f33.jpg)
代码
![](https://user-images.githubusercontent.com/16148054/145592206-239948b6-84ce-44d4-8905-14cda2c617d2.jpg)

一秒钟同时发送了好几封

**Comment by mashirozx** [comment]
解决了，等一下我重新提个pr
![IMG_20211210_233622](https://user-images.githubusercontent.com/16148054/145600689-f0f6b784-861d-4de1-8e65-a15046f4a211.jpg)
