### ISSUE TITLE
卡券没有限制每个用户只能使用一次的限制

### ISSUE THREAD

**Issue by kathylincn** [xflash-panda/v2board#4]
在生成优惠券的时候，没有每个用户的使用次数限制，导致能不停的使用。
比如生成一个5折的优惠券，用户能用不停的使用这个5折优惠券来续费。
应该可以限制这个优惠券每个用户是否只能使用一次。
这样他就只能续费或者新购优惠一次了。
（有人可能会说你可以生成使用1次的优惠券，那样要生成多少个才够别人使用？而且你没有每个用户使用次数限制的话
这种使用一次就失效的优惠券，别人也可以重复续费使用的，因为你优惠券不可能一次就发一张发100次吧，肯定都是100个一起发。）

**Comment by himanhimao** [comment]
这个功能已经有了
