### ISSUE TITLE
I can't access the account manager - admin#/user

### ISSUE THREAD

**Issue by thuanqt** [xflash-panda/v2board#5]
I can't access the account manager
请求失败
Server Error

**Comment by thuanqt** [comment]
setTelegramWebhook
请求失败
Server Error

**Comment by himanhimao** [comment]
必须外网，测试环境不可以

**Comment by himanhimao** [comment]
> I can't access the account manager 请求失败 Server Error

这是两个问题么？ 请描述的详细些，或者贴出截图。

**Comment by himanhimao** [comment]
> setTelegramWebhook 请求失败 Server Error

测试环境不可以，必须把应用部署到外网，这里有回调

**Comment by thuanqt** [comment]
> > setTelegramWebhook 请求失败 Server Error
> 
> 测试环境不可以，必须把应用部署到外网，这里有回调

应用部署在外网但仍然出错
