### ISSUE TITLE
telegram installation failed

### ISSUE THREAD

**Issue by thuanqt** [xflash-panda/v2board#6]
![image](https://user-images.githubusercontent.com/93050974/140306717-db38c2f0-4cc6-46bf-bc15-ebc34422182a.png)
![image](https://user-images.githubusercontent.com/93050974/140306745-3dea3537-cc76-45b3-9b43-b115e7f00c09.png)

**Comment by himanhimao** [comment]
打开调试日志 把报错发给我一下，找到.env文件，修改APP_DEBUG=true 
然后具体报错发我一下，可以从日志文件 或者调试窗口下

**Comment by thuanqt** [comment]
[2021-11-04 21:41:14] local.ERROR: Method App\Http\Controllers\Admin\ConfigController::setTelegramWebHook does not exist. {"exception":"[object]
